config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admin, skip: [:sessions, :passwords]



  devise_scope :admin do
    get "/admin/login" => "admin/sessions#new", as: :admin_session
    post "/admin/login" => "admin/sessions#create", as: :admin_login
    get "/admin/logout" => "admin/sessions#destroy", as: :admin_logout
  end

  authenticated do
    devise_scope :admin do
      namespace :admin do
        resources :blogs do
          collection do
            get "/confirm" => "blogs#confirm"
          end
          resources :comments, controller: "blogs/comments", only: [:index, :destroy]
        end
        get "/confirmation" => "blogs#confirm", as: :confirm
        root to: "top_page#show", as: :root
      end
    end
  end

  unauthenticated do
    devise_scope :admin do
      namespace :admin do
        root to: "sessions#new", as: :unauthenticated
      end
    end
  end

  get "/pages/*page", to: "pages#show"
  root "pages#show", page: "home"

  devise_for :users, path: "users", skip: [:sessions], controllers: {registrations: "users/registrations", confirmations: 'users/confirmations'}
  devise_scope :user do
    get "login" => "users/sessions#new", as: :user_session
    post "login" => "users/sessions#create", as: :user_login
    get "logout" => "users/sessions#destroy", as: :user_logout
    put "/users" => "users/registrations#update", as: :edit_user
    resources :comments, only: [:create]
    resources :authors, controller: "authors", only: [:index]

    resources :blogs, controller: "blogs" do
      resources :authors, controller: "blogs/authors", only: [:index]
    end

    post 'reactions/create'
    delete 'reactions/destroy'

    resources :users, only: [:show]
  end
end

app/models/blog.rb
class Blog < ApplicationRecord
  scope :sort_by_ASC, ->{order created_at: :asc}
  scope :sort_by_DESC, ->{order created_at: :desc}
  scope :sort_by_public_time, ->{order public_time: :desc}
  after_create :check_public
  after_update :check_public

  mount_uploader :intro_image, ImageUploader
  mount_uploader :author_image, ImageUploader

  BLOG_ATTRS = [:id, :title, :category_id, :public_time, :set_public,
    :suggest_status, :intro_image, :intro_image_cache,
    :content, :author_name, :author_position, :author_age, :author_image, :author_image_cache]

  belongs_to :category
  has_many :comments, dependent: :destroy
  has_many :reactions, dependent: :destroy

  validates :title, presence: true
  validates_length_of :title, maximum: 255
  validates :public_time, presence: true
  validates :intro_image, presence: true
  validates :author_name, presence: true
  validate :image_size_validation, if: :intro_image? || :author_image?
  validate :file_format
  validates_length_of :author_name, maximum: 32
  validates :author_position, presence: true
  validates_length_of :author_position, maximum: 32
  validates :author_age, presence: true, numericality: { only_integer: true,
                                                         greater_than: 0,
                                                         less_than: 100 }
  validates :content, presence: true
  validates_length_of :author_age, maximum: 32

  enum set_public: {forbids: Settings.blog.status.draft,
    allow: Settings.blog.status.published}

  enum public_status: {draft: Settings.blog.status.draft,
    published: Settings.blog.status.published}

  enum suggest_status: {unavailable: Settings.blog.suggest.unavailable,
    available: Settings.blog.suggest.available}

  def stop_public_blog
    update_attribute 'public_status', Blog.public_statuses[:draft]
  end

  def public_blog
    update_attribute 'public_status', Blog.public_statuses[:published]
  end

  def conditions_public_blog?
    return true if self.draft? && self.allow? && Time.now() > self.public_time
  end

  def check_public
    if self.allow? && (Time.now() >= self.public_time)
      self.public_blog
    else
      self.stop_public_blog
    end
  end

  def rate_like rate_tyle
    column = rate_tyle + "s_count"
    update_attribute "#{column}", (self.send(column)+1)
  end

  def unrate_like rate_tyle
    column = rate_tyle + "s_count"
    update_attribute "#{column}", (self.send(column)-1)
  end

  private
  def image_size_validation
    if intro_image.size > 2.megabytes
      errors.add(:intro_image, I18n.t("errors.size_image"))
    end
    if author_image.size > 2.megabytes
      errors.add(:author_image, I18n.t("errors.size_image"))
    end
  end

  def file_format
    unless valid_extension? self.intro_image.filename
      errors.add(:intro_image, I18n.t("errors.extenstion"))
    end
    unless valid_extension? self.author_image.filename
      errors.add(:author_image, I18n.t("errors.extenstion"))
    end
  end

  def valid_extension? filename
    return true if filename.nil?
    ext = File.extname(filename)
    %w(.jpg .png).include? ext.downcase
  end
end

app/controllers/admin/blogs/comments_controller.rb
class Admin::Blogs::CommentsController <  Admin::BaseAdminController
  before_action :find_blog, only: [:index, :destroy]

  def index
    @comments = @blog.comments
    respond_to do |format|
      format.js
    end
  end

  def destroy
    @comment = @blog.comments.find_by(id: params[:id]).destroy
    @comments = @blog.comments
    respond_to do |format|
      format.js
    end
  end

  private
  def find_blog
    @blog = Blog.find_by id: params[:blog_id]
  end
end

app/controllers/admin/blogs_controller.rb
class Admin::BlogsController < Admin::BaseAdminController
  before_action :set_ransack_object, only: [:index]
  before_action :convert_integer_parmas, only: [:create, :update, :confirm_post]
  before_action :convert_integer_parmas_confirm, only: [:confirm]
  before_action :find_blog, only: [:update, :edit, :destroy]

  def index
    result = @q.result(distinct: true)
    if params.has_key?(:sort_by) && !params[:sort_by].blank?
      result = result.send "sort_by_#{params[:sort_by]}"
    end
    @blogs = result.includes(:category).page(params[:page]).per(20)
    respond_to do |format|
      format.html
      format.js{render layout: false}
    end
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new blog_params
    if params[:action_type] == "create"
      @blog.intro_image = File.open(params[:image_path].to_s)
      unless params[:image_author_path].to_s.blank?
        @blog.author_image = File.open(params[:image_author_path].to_s)
      end
      if params[:commit] == t("admin.blog.create.form.back")
        render :new
      elsif params[:commit] == t("admin.blog.create.form.save")
        @blog.save
        @blog.check_public
        flash[:success] = t "alert.blog.create"
        redirect_to admin_blogs_path
      end
    else
      if @blog.valid?
        @image_path = @blog.intro_image.path
        @image_author_path = @blog.author_image.path
        @action = "create"
        render :confirm
      else
        render :new
      end
    end
  end

  def edit
  end

  def update
    @blog.stop_public_blog if params[:type] == "stop_public"
    @blog.public_blog if params[:type] == "public_blog"
    if params[:type] == "change_time"
      @blog.update_attribute "public_time", params[:blog]["public_time"]
      @blog.check_public
    end
    respond_to do |format|
      format.js{render layout: false}
      format.html do
        if params[:action_type] == "update"
          if params[:commit] == t("admin.blog.create.form.back")
            id = @blog.id
            intro_image = @blog.intro_image
            @blog = Blog.new blog_params
            @blog.id = id
            @blog.intro_image = File.open(params[:image_path].to_s)
            render :edit
          elsif params[:commit] == t("admin.blog.create.form.save")
            @blog.update_attributes blog_params
            @blog.update intro_image: File.open(params[:image_path].to_s)
            @blog.check_public
            flash[:success] = t "alert.blog.update"
            redirect_to admin_blogs_path
          end
        else
          if params[:blog][:intro_image].nil?
            @blog_instane = Blog.new(blog_params.merge(intro_image: @blog.intro_image))
          else
            @blog_instane = Blog.new blog_params
          end
          if @blog_instane.valid?
            @action = "update"
            render :confirm
          else
            @blog.update_attributes blog_params
            render :edit
          end
        end
      end
    end
  end

  def destroy
    if @blog.destroy
      flash[:success] = t "alert.blog.delete"
    end
    redirect_to admin_blogs_path
  end

  def confirm
    @blog = Blog.new blog_params
  end

  private
  def blog_params
    params.require(:blog).permit Blog::BLOG_ATTRS
  end

  def convert_integer_parmas
    if params[:blog]
      params[:blog][:set_public] = params[:blog][:set_public]
        .to_i
      params[:blog][:suggest_status] = params[:blog][:suggest_status]
        .to_i
    end
  end

  def convert_integer_parmas_confirm
    params[:set_public] = params[:set_public].to_i
    params[:suggest_status] = params[:suggest_status].to_i
  end

  def find_blog
    @blog = Blog.find_by id: params[:id]
    unless @blog
      redirect_to root_url
    end
  end

  def set_ransack_object
    @q = Blog.ransack params[:q]
  end
end

app/controllers/blogs/authors_controller.rb
class Blogs::AuthorsController < ApplicationController
  def index
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :find_blog, only: [:show]

  def index
    if params[:category].nil?
      if params[:get_suggest_action].eql? "suggest"
        @blogs = Blog.published.available.includes(:category).sort_by_public_time.page(params[:page]).per(10)
      else
        @blogs = Blog.published.includes(:category).sort_by_public_time.page(params[:page]).per(10)
      end
    else
      @blogs = Blog.published.where(category_id: params[:category].to_i).sort_by_public_time.includes(:category).page(params[:page]).per(10)
    end
    @category = Category.all
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    @blog_comments = @blog.comments.includes(:user).order('created_at ASC')
    if current_user
      @action = Reaction.where(user_id: current_user.id,
                               blog_id: @blog.id).first

      @check_action = @action.rate_type if @action
    else
      @check_action = cookies[:check_action]
    end
  end

  private
  def find_blog
    @blog = Blog.find_by id: params[:id]
    unless @blog
      redirect_to root_url
    end
  end
end

app/views/blogs/_blog.html.erb
<% @blogs.each do |blog| %>
  <li>
    <a href="<%= blog_path blog %>" style="text-decoration : none">
      <div class="row">
        <% if blog.suggest_status.eql?("available") %>
            <div class="promoted">
              <img src="/assets/promoted.png" alt="">
            </div>
        <% end %>
        <div class="intro-image col-xs-3">
          <%= image_tag blog.intro_image %>
        </div>
        <div class="blog col-xs-9">
          <div class="short-content">
            <p><%= blog.title %></p>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-6">
          <div class="category">
            <p><%= blog.category.name %></p>
          </div>
          <div class="publish-time">
            <p><%= format_date_in_list blog.public_time %></p>
          </div>
        </div>
        <div class="col-xs-6">
          <div class="col-xs-3 action">
            <img src="/assets/biglike.jpg" alt="">
            <span><p><%= blog.biglikes_count %></p></span>
          </div>
          <div class="col-xs-3 action">
            <span><img src="/assets/like.jpg" alt=""></span>
            <span><p><%= blog.likes_count %></p></span>
          </div>
          <div class="col-xs-3 action">
            <span><img src="/assets/dislike.jpg" alt=""></span>
            <span><p><%= blog.dislikes_count %></p></span>
          </div>
          <div class="col-xs-3 action">
            <span><img src="/assets/bigdislike.jpg" alt=""></span>
            <span><p><%= blog.bigdislikes_count %></p></span>
          </div>
        </div>
      </div>
    </a>
  </li>
<% end %>

app/views/blogs/_category.html.erb
<%= link_to blogs_path(type_action: "category"), remote: true do %>
    <li id="root" class="<%= params[:category].nil? ? "active" : "" %>" onclick="return active('root')">すべて</li>
<% end %>
<%= link_to blogs_path(type_action: "category", get_suggest_action: "suggest"), remote: true do %>
    <li id="suggest" onclick="return active('suggest')">オススメ</li>
<% end %>
<% @category.each do |category| %>
    <%= link_to blogs_path(category: category.id, type_action: "category"), remote: true do %>
        <li id="<%= category.id %>" onclick="return active(<%= category.id%>, <%= @category.count  %>)"><%=  category.name %></li>
    <% end %>
<% end %>
<%  %>
<%=  %>
<script>
  function active(num, category_count) {
      $(".slick-slide").find(".active").removeClass("active");
      if(num == 'root'){
          $("#root").addClass("active");
          $(".menu-bar ul .slick-list").css("margin-left", "-74vw");
      } else if(num == 'suggest'){
          $("#suggest").addClass("active");
          $(".menu-bar ul .slick-list").css("margin-left", "-23vw");
      } else {
          var idNum = "#" + num;
          $(idNum).addClass("active");
          if(num == (category_count - 1)){
            $(".menu-bar ul .slick-list").css("margin-left", "30vw");
          } else if (num == category_count){
              $(".menu-bar ul .slick-list").css("margin-left", "73vw");
          }else {
            $(".menu-bar ul .slick-list").css("margin-left", "-19vw");
          }
      }
  }
</script>

app/views/blogs/_reaction.html.erb
<div class="col-xs-3 action">
  <img src="/assets/biglike.jpg" alt="">
  <span><p><%= @blog.biglikes_count %></p></span>
</div>
<div class="col-xs-3 action">
  <span><img src="/assets/like.jpg" alt=""></span>
  <span><p><%= @blog.likes_count %></p></span>
</div>
<div class="col-xs-3 action">
  <span><img src="/assets/dislike.jpg" alt=""></span>
  <span><p><%= @blog.dislikes_count %></p></span>
</div>
<div class="col-xs-3 action">
  <span><img src="/assets/bigdislike.jpg" alt=""></span>
  <span><p><%= @blog.bigdislikes_count %></p></span>
</div>
<div class="hidden check-action" action="<%= @check_action %>"></div>

app/views/blogs/_social_share_btn.html.erb
<div class="col-xs-4 social social-share-button"  data-title="<%= @blog.title %>">
  <button class="btn-twitter" id="share-twitter" rel="nofollow " data-site="twitter" onclick="return SocialShareButton.share(this);">
    <img src="/assets/twitter" alt="">
  </button>
</div>
<div class="col-xs-4 social social-share-button" data-title="<%= @blog.title %>">
  <button class="btn-facebook" rel="nofollow " data-site="facebook" onclick="return SocialShareButton.share(this);" data-title="test">
    <img src="/assets/facebook" alt="">
  </button>
</div>
<div class="col-xs-4 social">
  <button class="btn-line">
    <% if false %>
      <div id="line-share-btn-ems" class="line-it-button" data-lang="en" data-type="share-c" data-url="<%= blog_url(@blog) %>"></div>
    <% end %>
    <div id="line-share-btn-ems" class="line-it-button" data-lang="en" data-type="share-c" data-url="<%= blog_url(@blog) %>"></div>
  </button>
</div>

<script>
  function shareLine() {
      LineIt.loadButton();
  }
</script>

app/views/blogs/index.html.erb
<div class="row menu-bar" >
  <ul class="autoplay">
    <%= render 'category' %>
  </ul>
</div>
<div class="main-view">
  <ul id="my-blogs-user" >
    <%= render 'blog' %>
  </ul>
  <% if @blogs.count.eql? 10 %>
    <% if params[:category].nil? %>
      <%= link_to 'Load More Posts', blogs_path(page: @blogs.next_page), class: 'load-more-posts', remote: true  %>
    <% else %>
      <%= link_to 'Load More Posts', blogs_path(page: @blogs.next_page, category: params[:category]), class: 'load-more-posts', remote: true  %>
    <% end %>
  <% end %>
</div>

app/views/blogs/index.js.erb
<% if params[:type_action].eql?("category") %>
  $("#my-blogs-user").html("<%= j render 'blog' %>");
<% else %>
  $("#my-blogs-user").append("<%= j render "blog" %>");
  <% if params[:category].nil? %>
    $('a.load-more-posts').attr('href', "<%= blogs_path page: @blogs.next_page %>");
  <% else %>
    $('a.load-more-posts').attr('href', "<%= blogs_path page: @blogs.next_page, category: params[:category] %>");
  <% end %>
  <% if @blogs.next_page.nil? %>
    $('a.load-more-posts').remove();
  <% end %>
<% end %>

app/views/blogs/show.html.erb
<div id="blog_detail_and_author">
  <div class="view-detail" id="view-detail">
    <div class="row">
      <% if @blog.suggest_status.eql?("available") %>
        <div class="promoted">
          <img src="/assets/promoted.png" alt="">
        </div>
      <% end %>
      <div class="blog">
        <div class="short-content">
          <p><%= @blog.title %></p>
        </div>
        <hr>
        <div class="row">
          <div class="col-xs-6">
            <div class="category">
              <p><%= @blog.category.name %></p>
            </div>
            <div class="publish-time">
              <p><%= format_date_in_list @blog.public_time %></p>
            </div>
          </div>
          <div class="col-xs-6" id="reaction-ems">
            <%= render 'reaction' %>
          </div>
        </div>
        <div class="row">
          <%= render 'social_share_btn' %>
        </div>
        <div class="row">
          <div class="content">
            <img src=<%= @blog.intro_image.url %> alt="">
            <p>
              <%= @blog.content.html_safe %>
            </p>
          </div>
        </div>
        <div class="row">
          <div class="author">
            <div class="row-image-info">
              <%= image_tag "author-image-blog.png" %>
              <div class="author-info">
                <p>この記事を書いた人</p>
                <div class="author-name">
                  <p><%= @blog.author_name %></p>
                </div>
                <p><%= @blog.author_position %> / <%= @blog.author_age %>歳</p>
              </div>
            </div>
            <div class="row-btn-detail">
              <button class="btn-detailed-author" id="btn_author" onclick="display_author_screen()" >
                <div class="row">
                  <p>ナルフォード先生のプロフィールを見る</p>
                  <img src="/assets/arrow.png" alt="">
                </div>
              </button>
            </div>
          </div>
        </div>
      </div>
      <div class="review" >
        <p class="review-title">参考になったかな？</p>
        <div class="row upper" >
          <div class="col-xs-6 left review-button " action="biglike" id="biglike">
            <img src="/assets/review-frame.png" alt="" class="review-frame">
            <img src="/assets/biglike.png" alt="" class="icon">
            <img src="/assets/review-white-frame.png" alt="" class="review-white-frame">
            <img src="/assets/tick.png" alt="" class="tick">
            <p>なるほど</p>
          </div>
          <div class="col-xs-6 review-button right" action="like" id="like">
            <img src="/assets/review-frame.png" alt="" class="review-frame">
            <img src="/assets/like.png" alt="" class="icon">
            <img src="/assets/review-white-frame.png" alt="" class="review-white-frame">
            <img src="/assets/tick.png" alt="" class="tick">
            <p>おもしろい</p>
          </div>
        </div>
        <div class="row lower" >
          <div class="col-xs-6 review-button left" action="dislike" id="dislike">
            <img src="/assets/review-frame.png" alt="" class="review-frame">
            <img src="/assets/dislike.png" alt="" class="icon">
            <img src="/assets/review-white-frame.png" alt="" class="review-white-frame">
            <img src="/assets/tick.png" alt="" class="tick">
            <p>難しい</p>
          </div>
          <div class="col-xs-6 review-button right" action="bigdislike" id="bigdislike">
            <img src="/assets/review-frame.png" alt="" class="review-frame">
            <img src="/assets/bigdislike.png" alt="" class="icon">
            <img src="/assets/review-white-frame.png" alt="" class="review-white-frame">
            <img src="/assets/tick.png" alt="" class="tick">
            <p>がっかり</p>
          </div>
        </div>
      </div>
      <div class="row comment">
        <p>ご意見・ご感想をお聞かせください</p>

        <div class="text-area" >
          <% if @blog_comments %>
              <% @blog_comments.order(:created_at).each do |comment| %>
                  <%= render 'comments/comment_message', comment: comment %>
              <% end %>
              <div id="comment_sentences">
              </div>
          <% end %>
          <br>
          <% if current_user %>
            <%= form_for Comment.new, method: :post, remote: true do |f| %>
              <%= f.text_area :content, placeholder: "投稿内容を入力してください" %>
              <%= f.hidden_field :blog_id, value: @blog.id %>
              <% if current_user %>
                  <%= f.hidden_field :user_id, value: current_user.id %>
              <% end %>
              <%= button_tag "送信する", id: "btn_comment" %>
            <% end %>
          <% end %>
        </div>
      </div>
      <div class="social-bottom">
        <div class="title-social">
          <img src="/assets/social-icon.png" alt="">
          <p>SNSでシェアする</p>
        </div>
        <%= render 'social_share_btn' %>
      </div>
    </div>
  </div>
</div>
<script>
    var check_user_action = "<%= @check_action %>"
    $(".review-button").removeClass("review-active");
    $("#"+ check_user_action).addClass("review-active");
    $(".review-button").on("click", function(){
        var get_action = $(this).attr("action");
        var check_action = $(".check-action").attr("action");
        $(".review-button").removeClass("review-active");
        if(get_action == check_action){
            $.ajax({
                url: "/reactions/destroy",
                dataType: "script",
                method: "delete",
                data: {
                    user_id: "<%= current_user ? current_user.id : "" %>",
                    blog_id: <%= @blog.id %>,
                    user_action: get_action
                }
            });
        } else {
            $(this).addClass("review-active");
            $.ajax({
                url: "/reactions/create",
                dataType: "script",
                method: "post",
                data: {
                    user_id: "<%= current_user ? current_user.id : "" %>",
                    blog_id: <%= @blog.id %>,
                    user_action: get_action
                }
            });
        }
    });
    function display_author_screen(){
        window.location.href = "<%= blog_authors_path(@blog) %>"
    }
</script>