config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admin, skip: [:sessions, :passwords]



  devise_scope :admin do
    get "/admin/login" => "admin/sessions#new", as: :admin_session
    post "/admin/login" => "admin/sessions#create", as: :admin_login
    get "/admin/logout" => "admin/sessions#destroy", as: :admin_logout
  end

  authenticated do
    devise_scope :admin do
      namespace :admin do
        resources :blogs do
          collection do
            get "/confirm" => "blogs#confirm"
          end
          resources :comments, controller: "blogs/comments", only: [:index, :destroy]
        end
        get "/confirmation" => "blogs#confirm", as: :confirm
        root to: "top_page#show", as: :root
      end
    end
  end

  unauthenticated do
    devise_scope :admin do
      namespace :admin do
        root to: "sessions#new", as: :unauthenticated
      end
    end
  end

  get "/pages/*page", to: "pages#show"
  root "pages#show", page: "home"

  devise_for :users, path: "users", skip: [:sessions], controllers: {registrations: "users/registrations", confirmations: 'users/confirmations'}
  devise_scope :user do
    get "login" => "users/sessions#new", as: :user_session
    post "login" => "users/sessions#create", as: :user_login
    get "logout" => "users/sessions#destroy", as: :user_logout
    put "/users" => "users/registrations#update", as: :edit_user
    resources :comments, only: [:create]
    resources :authors, controller: "authors", only: [:index]

    resources :blogs, controller: "blogs" do
      resources :authors, controller: "blogs/authors", only: [:index]
    end

    post 'reactions/create'
    delete 'reactions/destroy'

    resources :users, only: [:show]
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable, :confirmable,
  authentication_keys: [:email]

  mount_uploader :avatar, ImageUploader

  has_many :comments, dependent: :destroy
  has_many :reactions, dependent: :destroy
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  protected
  def after_confirmation_path_for(resource_name, resource)
    sign_in(resource)
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]
  before_action :current_domain, only: [:new]

  # GET /resource/registrations
  # def new
  #   super
  # end

  # POST /resource/registrations
  # def create
  #   super
  # end

  protected
  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :domain])
  end

  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :intro, :avatar, :avatar_cache])
  end

  def after_update_path_for(resource)
    user_path(current_user.id)
  end

  def current_domain
    @host = request.protocol + request.host_with_port
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find_by(id: params[:id])
  end
end

app/views/users/shared/_links.html.erb
<% if controller_name != 'sessions' %>
    <%= link_to t('sign_in', default: 'Sign in'), user_session_path %><br />
<% end %>

<% if devise_mapping.registerable? && controller_name != 'registrations' %>
    <%= link_to t('sign_up', default: 'Sign up'), user_registration_path %><br />
<% end %>

<% if false %>
  <% if devise_mapping.recoverable? && controller_name != 'passwords' %>
      <%= link_to t('.forgot_your_password', default: 'Forgot your password?'), new_password_path(resource_name) %><br />
  <% end %>

  <% if devise_mapping.confirmable? && controller_name != 'confirmations' %>
      <%= link_to t('.didn_t_receive_confirmation_instructions', default: "Didn't receive confirmation instructions?"), new_confirmation_path(resource_name) %><br />
  <% end %>

  <% if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
      <%= link_to t('.didn_t_receive_unlock_instructions', default: "Didn't receive unlock instructions?"), new_unlock_path(resource_name) %><br />
  <% end %>

  <% if devise_mapping.omniauthable? %>
      <% resource_class.omniauth_providers.each do |provider| %>
          <%= link_to t('.sign_in_with_provider', provider: provider.to_s.titleize, default: "Sign in with #{provider.to_s.titleize}"), omniauth_authorize_path(resource_name, provider) %><br />
      <% end %>
  <% end %>
<% end %>