config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admin, skip: [:sessions, :passwords]



  devise_scope :admin do
    get "/admin/login" => "admin/sessions#new", as: :admin_session
    post "/admin/login" => "admin/sessions#create", as: :admin_login
    get "/admin/logout" => "admin/sessions#destroy", as: :admin_logout
  end

  authenticated do
    devise_scope :admin do
      namespace :admin do
        resources :blogs do
          collection do
            get "/confirm" => "blogs#confirm"
          end
          resources :comments, controller: "blogs/comments", only: [:index, :destroy]
        end
        get "/confirmation" => "blogs#confirm", as: :confirm
        root to: "top_page#show", as: :root
      end
    end
  end

  unauthenticated do
    devise_scope :admin do
      namespace :admin do
        root to: "sessions#new", as: :unauthenticated
      end
    end
  end

  get "/pages/*page", to: "pages#show"
  root "pages#show", page: "home"

  devise_for :users, path: "users", skip: [:sessions], controllers: {registrations: "users/registrations", confirmations: 'users/confirmations'}
  devise_scope :user do
    get "login" => "users/sessions#new", as: :user_session
    post "login" => "users/sessions#create", as: :user_login
    get "logout" => "users/sessions#destroy", as: :user_logout
    put "/users" => "users/registrations#update", as: :edit_user
    resources :comments, only: [:create]
    resources :authors, controller: "authors", only: [:index]

    resources :blogs, controller: "blogs" do
      resources :authors, controller: "blogs/authors", only: [:index]
    end

    post 'reactions/create'
    delete 'reactions/destroy'

    resources :users, only: [:show]
  end
end

app/views/layouts/admin/_footer.html.erb
<div class="page-footer">
  <div class="page-footer-inner"> 2017 &copy; Terminal
    <a target="_blank" href="http://keenthemes.com">Keenthemes</a> &nbsp;|&nbsp;
  </div>
  <div class="scroll-to-top">
    <i class="icon-arrow-up"></i>
  </div>
</div>

app/views/layouts/admin/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="<%= admin_root_path %>"><%= t "layout.header.category.title" %></a>
    </div>
    <ul class="nav navbar-nav">
      <li class="dropdown <%= "active" if params[:controller] == "admin/blogs" %>">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          <%= t "layout.header.category.blog" %>
        </a>
        <ul class="dropdown-menu">
          <li>
            <%= link_to t("layout.header.category.list_blog"), admin_blogs_path %>
          </li>
          <li>
            <%= link_to t("layout.header.category.create_blog"), new_admin_blog_path %>
          </li>
        </ul>
      </li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li>
        <%= link_to t("layout.header.category.logout"), admin_logout_path %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/admin/base.html.erb
<!DOCTYPE html>
<html lang="en" class="ie8 no-js">
<html lang="en" class="ie9 no-js">
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <title><%= yield :title %></title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1" name="viewport"/>
    <meta content="" name="author"/>
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet"
          type="text/css"/>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application-admin", media: "all" %>
    <%= javascript_include_tag "application-admin" %>
    <link rel="shortcut icon" href="favicon.ico"/>
  </head>
  <body class="page-header-fixed page-sidebar-closed-hide-logo
          page-content-white">
    <div class="page-wrapper">
      <%= render "layouts/admin/header" %>
      <div class="clearfix"></div>
      <div class="page-container">
        <div class="page-content-wrapper">
          <div class="page-content layout-admin">
            <div class="container">
              <%= yield %>
            </div>
          </div>
        </div>
      </div>
      <br>

      <div id="modal-main-ems" class="modal fade" role="dialog">
        <div class="modal-dialog modal-dialog-comment-ems">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              <h4 class="modal-title"><%= t("admin.blog.table.comment") %></h4>
            </div>
            <div class="modal-body" id="modal-body-comment">
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>